require('devidas.plugins')
require('devidas.plugins.nvim-tree')
require('devidas.plugins.lualine')
require('devidas.plugins.telescope')
require('devidas.core.settings')
require('devidas.core.keybindings')
require('devidas.core.colorscheme')
